[build]
  command = ""
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  CACHE_URL = "some_id"
  OPENWEATHER_API_KEY = "35102437e50d37262084332662179159"

[context.deploy-preview.environment]
  OPENWEATHER_API_KEY = "35102437e50d37262084332662179159"

[context.branch-deploy.environment]
  OPENWEATHER_API_KEY = "35102437e50d37262084332662179159"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
